'use client';
import { useDashboard } from '@/contexts/DashboardContext';
import { FileText, Download, CheckCircle, Database, ShieldCheck, HardDrive } from 'lucide-react';
import { useState } from 'react';

export default function ReportsView() {
  const { system, alerts, traffic, devices, network } = useDashboard();
  const [downloading, setDownloading] = useState(false);

  // Status layanan nyata
  const onlineCount = devices.filter(d => d.status === 'online').length;
  const totalAlerts = alerts?.total_alerts ?? system?.total_alerts ?? 0;
  const criticalCount = alerts?.by_severity?.['CRITICAL'] ?? 0;
  const compliancePct = Math.max(0, 100 - totalAlerts);
  const complianceStatus = criticalCount > 0 ? 'REVIEW' : 'PASSED';
  const complianceColor = criticalCount > 0 ? '#f97316' : '#22c55e';

  const handleExportJSON = () => {
    setDownloading(true);
    const reportData = {
      generated_at: new Date().toISOString(),
      system_status: system,
      alerts_summary: alerts,
      total_packets_analyzed: system?.total_traffic ?? traffic.length,
      monitored_devices_count: devices.length,
      devices: devices,
      recent_traffic_sample: traffic.slice(0, 50)
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `UNG-Security-Audit-Report-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setDownloading(false);
  };

  return (
    <div className="flex-1 flex flex-col gap-3">
      {/* Report Header Card */}
      <div className="panel p-5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h2 className="text-base font-bold text-white">Executive Security Audit & Compliance Report</h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Generated by Unified Network Guard Intelligence Platform. ISO/IEC 27001 & IoT Security Standard.
          </p>
        </div>

        <button
          onClick={handleExportJSON}
          disabled={downloading}
          className="flex items-center gap-2 px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg text-xs font-bold transition-all shadow-[0_0_12px_rgba(6,182,212,0.4)]"
        >
          <Download className="w-4 h-4" />
          <span>{downloading ? 'Exporting...' : 'Export Audit JSON'}</span>
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div className="panel p-4 flex flex-col justify-between">
          <div className="flex justify-between items-center text-xs text-slate-400">
            <span>Database Integrity</span>
            <Database className="w-4 h-4 text-green-400" />
          </div>
          <div className="text-xl font-bold text-white mt-2 flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-green-500 shadow-[0_0_8px_#22c55e]"></span>
            <span className="capitalize">{system?.database || 'Connected'}</span>
          </div>
          <div className="text-[10px] text-slate-400 mt-1">PostgreSQL 15 Alpine</div>
        </div>

        <div className="panel p-4 flex flex-col justify-between">
          <div className="flex justify-between items-center text-xs text-slate-400">
            <span>Total Captured Packets</span>
            <HardDrive className="w-4 h-4 text-blue-400" />
          </div>
          <div className="text-xl font-bold text-white mt-2 font-mono">
            {(system?.total_traffic ?? 0).toLocaleString()}
          </div>
          <div className="text-[10px] text-slate-400 mt-1">Scapy Raw Socket Sniffer</div>
        </div>

        <div className="panel p-4 flex flex-col justify-between">
          <div className="flex justify-between items-center text-xs text-slate-400">
            <span>Compliance Assessment</span>
            <ShieldCheck className="w-4 h-4 text-cyan-400" />
          </div>
          <div className="text-xl font-bold font-mono mt-2" style={{ color: complianceColor }}>
            {compliancePct}% {complianceStatus}
          </div>
          <div className="text-[10px] text-green-400 mt-1">
            {criticalCount === 0
              ? 'Tanpa alert critical — skor penuh'
              : `${criticalCount} alert critical perlu tindak lanjut`}
          </div>
        </div>
      </div>

      {/* Audit Log Overview */}
      <div className="panel p-4 flex-1 flex flex-col min-h-[380px]">
        <h3 className="text-sm font-bold text-white mb-3">Audit Trails & Telemetry Summary</h3>

        <div className="space-y-2 text-xs font-mono text-slate-300 overflow-auto">
          <div className="p-2.5 rounded bg-[#0b0e17] border border-white/5 flex justify-between items-center">
            <span>[SYS-STATUS] API Gateway v1.0.0 Online (Uvicorn + FastAPI)</span>
            <span className={`font-bold ${system ? 'text-green-400' : 'text-red-400'}`}>{system ? 'HEALTHY' : 'OFFLINE'}</span>
          </div>
          <div className="p-2.5 rounded bg-[#0b0e17] border border-white/5 flex justify-between items-center">
            <span>[MQTT-BROKER] Mosquitto 2.0 MQTT Service at port 1883</span>
            <span className={`font-bold ${onlineCount > 0 ? 'text-green-400' : 'text-amber-400'}`}>{onlineCount > 0 ? 'LISTENING' : 'IDLE'}</span>
          </div>
          <div className="p-2.5 rounded bg-[#0b0e17] border border-white/5 flex justify-between items-center">
            <span>[SNIFFER-INTERFACE] Raw Scapy packet capture attached to {network?.interface || '—'}</span>
            <span className={`font-bold ${(system?.total_traffic ?? 0) > 0 ? 'text-green-400' : 'text-amber-400'}`}>{(system?.total_traffic ?? 0) > 0 ? 'RUNNING' : 'IDLE'}</span>
          </div>
          <div className="p-2.5 rounded bg-[#0b0e17] border border-white/5 flex justify-between items-center">
            <span>[SURICATA-EVE] IDS engine — log /var/log/suricata/eve.json</span>
            <span className={`font-bold ${system?.suricata_online ? 'text-green-400' : 'text-amber-400'}`}>{system?.suricata_online ? 'RUNNING' : 'NOT RUNNING'}</span>
          </div>
          <div className="p-2.5 rounded bg-[#0b0e17] border border-white/5 flex justify-between items-center">
            <span>[ML-ISOLATION-FOREST] Anomaly prediction pipeline trained and ready</span>
            <span className="font-bold text-cyan-400">{system ? 'ACTIVE' : 'OFFLINE'}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
